version = 2
platform = "windows"

[app]
id = "downloaded_test"
name = "Downloaded Test"
process_name = "explorer.exe"
default_focus_state = "global"
default_tags = ["downloaded", "test"]

[actions.open_emoji_panel]
name = "Open emoji panel"
focus_state = "global"
priority = "medium"
cmd = { mods = ["win"], key = "Period" }
