version = 3
platform = "windows"
process_name = "Explorer.EXE"

[actions]

[actions.new_tab]
cmd = { mods = ["ctrl"], key = "KeyT" }

[actions.close_tab]
cmd = { mods = ["ctrl"], key = "KeyW" }

[actions.next_tab]
cmd = { mods = ["ctrl"], key = "Tab" }

[actions.previous_tab]
cmd = { mods = ["ctrl", "shift"], key = "Tab" }

[actions.new_window]
cmd = { mods = ["ctrl"], key = "KeyN" }

[actions.new_folder]
cmd = { mods = ["ctrl", "shift"], key = "KeyN" }

[actions.rename_item]
cmd = { mods = [], key = "F2" }

[actions.refresh]
cmd = { mods = [], key = "F5" }

[actions.search]
cmd = { mods = ["ctrl"], key = "KeyE" }

[actions.focus_address_bar]
cmd = { mods = ["alt"], key = "KeyD" }

[actions.show_properties]
cmd = { mods = ["alt"], key = "Enter" }

[actions.go_back]
cmd = { mods = ["alt"], key = "LeftArrow" }

[actions.go_forward]
cmd = { mods = ["alt"], key = "RightArrow" }

[actions.go_up_level]
cmd = { mods = ["alt"], key = "UpArrow" }

[actions.toggle_preview_pane]
cmd = { mods = ["alt"], key = "KeyP" }

[actions.toggle_details_pane]
cmd = { mods = ["alt", "shift"], key = "KeyP" }

[actions.expand_all_folders]
cmd = { mods = ["ctrl", "shift"], key = "KeyE" }

[actions.delete_selected_item]
cmd = { mods = [], key = "Delete" }

[actions.delete_selected_item_permanently]
cmd = { mods = ["shift"], key = "Delete" }

[actions.scroll_to_top]
cmd = { mods = [], key = "Home" }

[actions.scroll_to_bottom]
cmd = { mods = [], key = "End" }

[actions.cycle_window_elements]
cmd = { mods = [], key = "F6" }

[actions.toggle_fullscreen]
cmd = { mods = [], key = "F11" }

[actions.collapse_selection]
cmd = { mods = [], key = "LeftArrow" }

[actions.expand_selection]
cmd = { mods = [], key = "RightArrow" }

[actions.show_context_menu]
cmd = { mods = ["shift"], key = "F10" }
